portfolio_user_homepage:
    path:     /hello
    defaults: { _controller: PortfolioUserBundle:Default:index }
portfolio_user_test:
    path:     /test
    defaults: { _controller: PortfolioUserBundle:Default:test }